services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: iceaxe
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: iceaxe_test_db
    ports:
      - "5438:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

volumes:
  postgres_data_test:
